### ISSUE TITLE
Something went wrong on Debian 9

### ISSUE THREAD

**Issue by hakavlad** [tobixen/thrash-protect#21] opened 2019-03-15 02:52 UTC
I just ran thrash-protect, and get next output:
http://okturing.com/src/5948/body

It was an unpleasant experience: it stopped my browser and virtualbox, then  I had to kill thrash-protect, and manually send SIGCONT to stopped processes.

**Comment by tobixen** [comment] 2019-03-15 05:35
This is a duplicate of #18, I have a hard coded assumption that the system is already thrashing if the main loop takes "too long" time to execute - I've never observed this failing personally, but obviously systems are different.  I'll think a bit and either drop this check completely or come with a workaround.

**Closed by tobixen** 2019-03-15 05:35 UTC
